repository_type: pipeline

lint:
  files_exist:
    - assets/nf-core-speciesabundance_logo_light.png
    - docs/images/nf-core-speciesabundance_logo_light.png
    - docs/images/nf-core-speciesabundance_logo_dark.png
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - assets/sendmail_template.txt
    - assets/email_template.html
    - lib/NfcoreTemplate.groovy
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - assets/email_template.txt
    - docs/README.md
    - LICENSE
  pipeline_name_conventions: False
  actions_awsfulltest: False
  multiqc_config:
    - report_comment
  nextflow_config:
    - custom_config
    - manifest.name
    - manifest.homePage
  readme:
    - nextflow_badge
